# Generated by Django 5.0.6 on 2024-08-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='calificacion',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
